'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BrewersAssistant.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to s.
        '''</summary>
        Friend ReadOnly Property ArduinoSetupString() As String
            Get
                Return ResourceManager.GetString("ArduinoSetupString", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Finished.
        '''</summary>
        Friend ReadOnly Property CompleteBrewingSessionButtonTitle() As String
            Get
                Return ResourceManager.GetString("CompleteBrewingSessionButtonTitle", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to finish this brew session?.
        '''</summary>
        Friend ReadOnly Property CompleteBrewiningSessionButtonText() As String
            Get
                Return ResourceManager.GetString("CompleteBrewiningSessionButtonText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 00.00.
        '''</summary>
        Friend ReadOnly Property DefaultDecimal() As String
            Get
                Return ResourceManager.GetString("DefaultDecimal", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this record?.
        '''</summary>
        Friend ReadOnly Property DeleteSessionButtonText() As String
            Get
                Return ResourceManager.GetString("DeleteSessionButtonText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property DeleteSessionTitleText() As String
            Get
                Return ResourceManager.GetString("DeleteSessionTitleText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to g.
        '''</summary>
        Friend ReadOnly Property HLPumpOff() As String
            Get
                Return ResourceManager.GetString("HLPumpOff", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to c.
        '''</summary>
        Friend ReadOnly Property HLPumpON() As String
            Get
                Return ResourceManager.GetString("HLPumpON", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Mash Pump Off.
        '''</summary>
        Friend ReadOnly Property MashButtonOffText() As String
            Get
                Return ResourceManager.GetString("MashButtonOffText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Mash Pump Running.
        '''</summary>
        Friend ReadOnly Property MashButtonOnText() As String
            Get
                Return ResourceManager.GetString("MashButtonOnText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to h.
        '''</summary>
        Friend ReadOnly Property MashPumpOff() As String
            Get
                Return ResourceManager.GetString("MashPumpOff", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to d.
        '''</summary>
        Friend ReadOnly Property MashPumpOn() As String
            Get
                Return ResourceManager.GetString("MashPumpOn", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to RIM Heat Off.
        '''</summary>
        Friend ReadOnly Property RimButtonOffText() As String
            Get
                Return ResourceManager.GetString("RimButtonOffText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to RIM Heating.
        '''</summary>
        Friend ReadOnly Property RimButtonOnText() As String
            Get
                Return ResourceManager.GetString("RimButtonOnText", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to b.
        '''</summary>
        Friend ReadOnly Property RimOff() As String
            Get
                Return ResourceManager.GetString("RimOff", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to a.
        '''</summary>
        Friend ReadOnly Property RimOn() As String
            Get
                Return ResourceManager.GetString("RimOn", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
